export const GO_NEXT_STEP = 'GO_NEXT_STEP';
export const GO_PREVIOUS_STEP = 'GO_PREVIOUS_STEP';

// export const INPUT_CHANGE = 'INPUT_CHANGE';
export const SAVE_STEP_ONE_DATA = 'SAVE_STEP_ONE_DATA';
export const SAVE_STEP_TWO_DATA = 'SAVE_STEP_TWO_DATA';

export const CHECKBOX_CHANGE = 'CHECKBOX_CHANGE';


// export const EMAIL_CHANGE = 'EMAIL_CHANGE';
// export const PASSWORD_CHANGE = 'PASSWORD_CHANGE';
// export const PASSWORD_CONFIRM_CHANGE = 'PASSWORD_CONFIRM_CHANGE';
